---
- hosts: fixtures
  vars:
    username: admin
    password: changeme
    server_url: https://192.168.123.230
  tasks:
  - name: Update repositories
    katello_repository:
      username: "{{ username }}"
      password: "{{ password }}"
      server_url: "{{ server_url }}"
      verify_ssl: false
      state: present
      name: "{{ item.name }}"
      #label: "{{ item.label }}"
      organization: "{{ item.organization }}"
      docker_upstream_name: "{{ item.docker_upstream_name }}"
      url: "{{ item.url }}"
      product: "{{ item.product }}"
      content_type: "{{ item.content_type }}"
      download_policy: "{{ item.download_policy | default(omit) }}"
    with_items:
      - name: "rhel7/etcd"
        docker_upstream_name: "rhel7/etcd"
        label: "rhel7_etcd"
        product: "Red Hat Container Catalog"
        organization: "Example Corporation"
        content_type: "docker"
        url: "https://registry.access.redhat.com"

