---
- yum:
    name: docker
    state: latest

- group:
    name: docker
    state: present

- user:
    name: vagrant
    groups: docker
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- lineinfile:
    dest: /etc/sysconfig/docker
    regexp: "OPTIONS='--selinux-enabled --log-driver=journald'"
    line: "OPTIONS='--selinux-enabled -G docker --log-driver=journald'"

- service:
    name: docker
    state: restarted
