---
- lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication no'
    line: 'PasswordAuthentication yes'
    state: present

# To create password hash:
# sudo pip install passlib
# python
# >>> from passlib.hash import sha512_crypt
# >>> hash = sha512_crypt.encrypt("redhat")
# >>> hash
#
- user:
    name: "{{ item }}"
    password: $6$rounds=656000$CsDa/IE/YYn1JQd1$sDaDOUk4oHPO6dk3Dhvukl89PuwFVQaSufK4OZKEOZQ2SAfPAnrB.tEf/3fG9qYosv524jk1ivP.fX3xQhGIl.
    update_password: always
    generate_ssh_key: yes
    createhome: no
    force: yes
  with_items:
  - root
  - vagrant
