- hosts: all
  become: true
  tasks:
  # docker
  - yum:
      name: docker
      state: latest
  - group:
      name: docker
      state: present
  - user:
      name: vagrant
      groups: docker
      append: yes
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
  - lineinfile:
      dest: /etc/sysconfig/docker
      regexp: "OPTIONS='--selinux-enabled --log-driver=journald'"
      line: "OPTIONS='--selinux-enabled -G docker --log-driver=journald'"
  - file:
      path: /home/vagrant/.docker
      state: directory
    become_user: vagrant
  - template:
      src: /home/thomasmckay/code/tmp/quay-config.json
      dest: /home/vagrant/.docker/config.json
  - service:
      name: docker
      state: restarted

  - yum:
      name: python-pip
      state: latest
  - command: pip install docker-py

  - file:
      path: /home/vagrant/quay-storage
      state: directory
    become_user: vagrant
  - file:
      path: /home/vagrant/quay-config
      state: directory
    become_user: vagrant

  - name: pull quay image
    docker_image:
      name: quay.io/coreos/quay
      tag: v2.8.0
    become_user: vagrant
  - name: pull redis image
    docker_image:
      name: quay.io/quay/redis
      tag: latest
  - name: pull mysql image
    docker_image:
      name: mysql
      tag: 5.7

  - name: redis container
    docker:
      name: redis
      image: quay.io/quay/redis
      state: started
      ports:
      - "6379:6379"

  - name: mysql container
    docker:
      name: mysql
      image: mysql:5.7
      state: started
      ports:
      - "3306:3306"
      env:
        MYSQL_USER: coreosuser
        MYSQL_DATABASE: enterpriseregistrydb
        MYSQL_CONTAINER_NAME: mysql
        MYSQL_ROOT_PASSWORD: 10hWfe6cns3lNEOIp5Q0hiEtABBDYaMn
        MYSQL_PASSWORD: 10hWfe6cns3lNEOIp5Q0hiEtABBDYaMn

  - name: quay container
    docker:
      name: quay
      image: quay.io/coreos/quay:v2.8.0
      state: started
      restart_policy: always
      ports:
      - "80:80"
      - "443:443"
      volumes:
      - /home/vagrant/quay-config:/conf/stack
      - /home/vagrant/quay-storage:/datastorage
